# Generated by Django 4.0.6 on 2022-07-04 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_app', '0002_remove_message_dialog_remove_ticket_dialog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Active', 'Активно'), ('Solved', 'Решено'), ('Unsolved', 'Не решено'), ('Frozen', 'Заморожено')], default='Active', max_length=10),
        ),
    ]
