# Generated by Django 4.0.6 on 2022-07-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_app', '0004_alter_message_author_alter_ticket_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(max_length=500, verbose_name='Сообщене'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Описание'),
        ),
    ]
