# Generated by Django 4.0.6 on 2022-07-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_app', '0006_alter_message_author_alter_message_is_read_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('solved', 'solved'), ('unsolved', 'unsolved'), ('frozen', 'frozen')], default='active', max_length=10, verbose_name='Status'),
        ),
    ]
