# Generated by Django 4.0.6 on 2022-07-11 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_app', '0007_remove_message_is_read_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Message date'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date'),
        ),
    ]
